using System.ComponentModel.DataAnnotations;

namespace QuestionBankApi.Core.Dtos
{
    public class Verify2FADto
    {

        [Required]
        public string Username { get; set; }

        [Required]
        public string Code { get; set; }  // The TOTP code generated by the authenticator app
    }
}

